"""add hashed_password to users

Revision ID: cb59d5fda74b
Revises: cb2795df4360
Create Date: 2026-06-25 02:10:07.576706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb59d5fda74b'
down_revision: Union[str, Sequence[str], None] = 'cb2795df4360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
